'use server';

import { createServerSupabaseClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';

export interface SystemSetting {
    key: string;
    value: string;
    description: string;
}

export async function getSystemSetting(key: string): Promise<string | null> {
    const supabase = await createServerSupabaseClient();

    // Auth Check
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) return null;

    const { data, error } = await (supabase
        .from('system_settings') as any)
        .select('value')
        .eq('key', key)
        .single();

    if (error) return null;
    return data.value;
}

import { syncToGoogleSheet } from '@/lib/google-sheets';

export async function updateSystemSetting(key: string, value: string) {
    try {
        const supabase = await createServerSupabaseClient();

        // Auth Check
        const { data: { user }, error: authError } = await supabase.auth.getUser();
        if (authError || !user) throw new Error('Unauthorized');

        // Cast as any because system_settings table type is missing in autogenerated types
        const { error } = await (supabase
            .from('system_settings') as any)
            .upsert({ key, value });

        if (error) throw new Error(error.message);

        revalidatePath('/admin/settings/integrations');
        return { success: true };
    } catch (error: any) {
        console.error('Update Setting Error:', error);
        return { success: false, error: error.message };
    }
}

export async function syncGoogleSheetAction() {
    try {
        const supabase = await createServerSupabaseClient();

        // Auth Check
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) throw new Error('Unauthorized - Inicia sesión nuevamente');

        // 1. Get Sheet ID
        const { data: setting, error: settingError } = await (supabase
            .from('system_settings') as any)
            .select('value')
            .eq('key', 'google_sheet_id')
            .single();

        const sheetId = setting?.value;
        if (!sheetId) throw new Error('Google Sheet ID no configurado. Guárdalo primero.');

        // 1.5 Get Private Key Override (Rescue for Vercel Env Issues)
        const { data: keySetting } = await (supabase
            .from('system_settings') as any)
            .select('value')
            .eq('key', 'google_private_key_override')
            .single();

        const privateKeyOverride = keySetting?.value;

        // 2. Get Data from AI View
        const { data: ads, error: adsError } = await (supabase as any)
            .from('ai_knowledge_base')
            .select('*');

        if (adsError) throw new Error(`Error leyendo DB (View): ${adsError.message}`);

        // 3. Sync
        await syncToGoogleSheet(
            ads,
            { spreadsheetId: sheetId, sheetName: 'BotData' },
            privateKeyOverride ? { private_key: privateKeyOverride } : undefined
        );

        revalidatePath('/admin/settings/integrations');
        return { success: true, count: ads.length };

    } catch (error: any) {
        console.error('Sync Action Critical Error:', error);
        // Devuelve el error para mostrarlo en el Toast
        return { success: false, error: error.message || 'Error interno del servidor' };
    }
}
